services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "${PORT}:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    networks:
      - app-network

  # הוספת Frontend service
  frontend:
    build: ./frontend_
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:${PORT}/api
      - REACT_APP_ADMIN_PHONE=${ADMIN_PHONE}
      - REACT_APP_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend_:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge